networks:
  app_network:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    networks:
      - app_network
    container_name: nginx
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf
